import = [
    #"~/.config/alacritty/themes/themes/terminal_app.toml"
    "~/.local/share/nvim/site/pack/paqs/start/zenbones.nvim/extras/alacritty/forestbones_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 18.0
offset = { x = 0, y = -2 }

[font.normal]
family = "LXGW WenKai Mono"
style = "Light"

[window]
decorations = "Buttonless"
padding = { x = 15, y = 15 }
dynamic_padding = true
option_as_alt = "Both"
opacity = 1

[scrolling]
history = 100000

[[keyboard.bindings]]
key = "H"
mods = "Command"
chars = "\u001bh"

[[keyboard.bindings]]
key = "J"
mods = "Command"
chars = "\u001bj"

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\u001bk"

[[keyboard.bindings]]
key = "L"
mods = "Command"
chars = "\u001bl"

# dark
[colors.primary]
background = '#242d2c'
#
#[colors.normal]
#black   = '#090618'
#red     = '#c34043'
#green   = '#76946a'
#yellow  = '#c0a36e'
#blue    = '#7e9cd8'
#magenta = '#957fb8'
#cyan    = '#6a9589'
#white   = '#c8c093'
#
#[colors.bright]
#black   = '#727169'
#red     = '#e82424'
#green   = '#98bb6c'
#yellow  = '#e6c384'
#blue    = '#7fb4ca'
#magenta = '#938aa9'
#cyan    = '#7aa89f'
#white   = '#dcd7ba'
#
#[colors.selection]
#background = '#2d4f67'
#foreground = '#c8c093'
#
#[[colors.indexed_colors]]
#index = 16
#color = '#ffa066'
#
#[[colors.indexed_colors]]
#index = 17
#color = '#ff5d62'
