#!/bin/sh
set -e

MODE="$1"

if [ -z "$MODE" ]; then
    echo "Usage: $0 push|pull"
    exit 1
fi

copy_file() {
    SRC="$1"
    DEST="$2"
    if [ "$MODE" = "pull" ]; then
        cp "$SRC" "$DEST"
    elif [ "$MODE" = "push" ]; then
        cp "$DEST" "$SRC"
    else
        echo "Invalid mode: $MODE"
        exit 1
    fi
}

# Scripts
for s in \
    24-bit-color.sh \
    age \
    battery \
    clock-emoji \
    cpu-usage \
    disk-usage \
    memory-usage \
    osoneline \
    testnerd \
    tmux-api \
    tmux-init \
    tmux-sessions \
    tofi \
    upt
do
    copy_file ~/Scripts/$s Scripts/$s
done

# Desktop env
copy_file ~/.config/hypr/hyprland.conf hypr/hyprland.conf
copy_file ~/.config/waybar/config.jsonc waybar/config.jsonc
copy_file ~/.config/waybar/style.css waybar/style.css

# Terminal
copy_file ~/.config/kitty/kitty.conf kitty
copy_file ~/.tmux.conf .tmux.conf

# Neovim
copy_file ~/.config/nvim/init.lua nvim/init.lua
