#!/bin/sh
set -e

MODE="$1"

if [ -z "$MODE" ]; then
    echo "Usage: $0 push|pull"
    exit 1
fi

copy_file() {
    SRC="$1"
    DEST="$2"
    if [ "$MODE" = "pull" ]; then
        cp "$SRC" "$DEST"
    elif [ "$MODE" = "push" ]; then
        cp "$DEST" "$SRC"
    else
        echo "Invalid mode: $MODE"
        exit 1
    fi
}

# Scripts
for s in \
    24-bit-color.sh \
    age \
    autostart \
    battery \
    clock-emoji \
    cpu-usage \
    disk-usage \
    memory-usage \
    osoneline \
    overnuke \
    testnerd \
    tmux-api \
    tmux-init \
    tmux-sessions \
    tofi \
    upt \
    uvfreeze
do
    copy_file ~/Scripts/$s Scripts/$s
done

# Desktop env
case "$OSTYPE" in
	"darwin"*)
		;;
	*)
		# x
		copy_file ~/.xinitrc .xinitrc
		copy_file ~/.xprofile .xprofile
		copy_file ~/.Xresources .Xresources

		# i3
		copy_file ~/.config/i3/config i3/config
		copy_file ~/.config/polybar/config.ini polybar/config.ini

		# desktop app theming
		copy_file ~/.gtkrc-2.0 .gtkrc-2.0
		copy_file ~/.config/gtk-3.0/settings.ini gtk-3.0/settings.ini
		copy_file ~/.config/gtk-4.0/settings.ini gtk-4.0/settings.ini

		# fcitx
		copy_file ~/.config/fcitx5/config fcitx5/config
esac

# Terminal
copy_file ~/.config/kitty/kitty.conf kitty/kitty.conf
copy_file ~/.tmux.conf .tmux.conf

# Neovim
copy_file ~/.config/nvim/init.lua nvim/init.lua
