#!/bin/bash
cpscript() {
  cp ~/Scripts/$1 Scripts
}

cpscript 24-bit-color.sh
cpscript age
cpscript always200
cpscript battery
cpscript clock-emoji
cpscript cpu-usage
cpscript disk-usage
cpscript memory-usage
cpscript next-event
cpscript osoneline
cpscript sunrise
cpscript sunrise-server
cpscript testnerd
cpscript tmux-sessions
cpscript tofi
cpscript upt

# desktop env
cp -r ~/.config/hypr .
cp -r ~/.config/waybar .

# terminal
cp -r ~/.config/kitty/kitty.conf kitty
cp ~/.tmux.conf .

# neovim
cp -r ~/.config/nvim/init.lua nvim

# vscode
cp ~/Library/Application\ Support/Code/User/settings.json vscode
