#!/bin/bash
cpscript() {
  cp ~/Scripts/$1 Scripts
}

cpscript 24-bit-color.sh
cpscript age
cpscript always200
cpscript battery
cpscript clock-emoji
cpscript cpu-usage
cpscript disk-usage
cpscript memory-usage
cpscript next-event
cpscript sunrise
cpscript sunrise-server
cpscript testnerd
cpscript tmux-sessions
cpscript upt

cp -r ~/.config/nvim/init.lua nvim
cp -r ~/.config/kitty/kitty.conf kitty
cp ~/.tmux.conf .
