#!/bin/bash

# kill
killall fcitx5
killall polybar

# monitors
MONITOR_SETUP="$HOME/.screenlayout/apply.sh"
[ -f $MONITOR_SETUP ] && $MONITOR_SETUP

# input setup
setxkbmap -option caps:numlock

# startup apps that should be also refreshed on wm refresh
# you may need to also add them to the kill section to avoid duplicates
#
# (put one time execution apps in ~/.xinitrc)
blueman-applet & disown
nm-applet & disown
fcitx5 -d
polybar & disown
