#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  productVersion=$(sw_vers -productVersion)
  majorVersion=$(echo "$productVersion" | cut -d. -f1)

  case $majorVersion in
    11) name="Big Sur" ;;
    12) name="Monterey" ;;
    13) name="Ventura" ;;
    14) name="Sonoma" ;;
    15) name="Sequoia" ;;
     *) name="" ;;
  esac
  echo "🍎 macOS $productVersion ($name)"

else
  echo "🐧 $(awk -F= '/^NAME=|^VERSION=/{gsub(/"/,""); printf "%s ", $2}' /etc/os-release | sed 's/ $/\n/') "

fi
