#!/bin/bash

# Check if the operating system is macOS
if [[ "$OSTYPE" == "darwin"* ]]; then
  
  # --- macOS ---
  # Get the full version string, e.g., "14.5"
  productVersion=$(sw_vers -productVersion)
  # Extract just the major version number, e.g., "14"
  majorVersion=$(echo "$productVersion" | cut -d. -f1)
  
  # A 'case' statement to map the major version number to its marketing name
  case $majorVersion in
    11) name="Big Sur" ;;
    12) name="Monterey" ;;
    13) name="Ventura" ;;
    14) name="Sonoma" ;;
    15) name="Sequoia" ;;
     *) name="" ;;
  esac
  
  # Print the emoji, product name, marketing name, and version number
  echo "🍎 macOS $productVersion ($name)"

else
  
  # --- Linux ---
  # This part is for other OS types, assumed to be Linux with /etc/os-release
  # It gets the NAME and VERSION fields and prints them.
  echo "🐧 $(awk -F= '/^NAME=|^VERSION=/{gsub(/"/,""); printf "%s ", $2}' /etc/os-release | sed 's/ $/\n/') "

fi
