#!/bin/sh

source "./tmux-api"

session "1_bench"
window "1" "1" "btop"

session "2_config"
window "2" "1" "cd ~/.config/kitty && nvim kitty.conf" "kitty"
window "2" "2" "nvim ~/.tmux.conf" "tmux"
window "2" "3" "nvim ~/.config/" "nvim"
window "2" "6" "cd ~/.config/hypr && nvim hyprland.conf" "hypr"
window "2" "8" "cd ~/Code/dotfiles2" "dotfiles"

[ -f "./tmux-init-user" ] && ./tmux-init-user

tmux attach
