#!/usr/bin/env bash

source "$HOME/Scripts/tmux-api"

if [[ "$OSTYPE" == "darwin"* ]]; then
	MACOS=1
else
	LINUX=1
fi


session "1"
window "1" "1" "cd ~/Code/dotfiles2" "dotfiles"
window "1" "2" "cd ~/.config/nvim && nvim init.lua" "nvim"
window "1" "3" "nvim ~/.tmux.conf" "tmux"
window "1" "4" "cd ~/Scripts && nvim" "Scripts"
window "1" "5" "nvim ~/.zshrc" "zshrc"
[[ -n "$LINUX" ]] && window "1" "6" "nvim ~/.config/i3/config ~/Scripts/autostart ~/.config/polybar/config.ini ~/Scripts/tmux-init ~/Scripts/tmux-init-user" "wm"

tmux attach
