#!/bin/bash
if [[ "$OSTYPE" == "darwin"* ]]; then
	boot_time=$(sysctl -n kern.boottime | awk '{print $4}' | tr -d ',')
	current_time=$(date +%s)
	uptime_seconds=$((current_time - boot_time))
	days=$((uptime_seconds / 86400))
	hours=$(((uptime_seconds % 86400) / 3600 ))
	minutes=$(((uptime_seconds % 3600) / 60 ))
	printf "%dd%dh%dm\n" $days $hours $minutes
else
	uptime_seconds=$(awk '{print int($1)}' /proc/uptime)

	days=$((uptime_seconds / 86400))
	hours=$(((uptime_seconds % 86400) / 3600))
	minutes=$(((uptime_seconds % 3600) / 60))

	printf "%dd%dh%dm\n" "$days" "$hours" "$minutes"
fi
