#!/bin/bash
boot_time=$(sysctl -n kern.boottime | awk '{print $4}' | tr -d ',')
current_time=$(date +%s)
uptime_seconds=$((current_time - boot_time))
days=$((uptime_seconds / 86400))
hours=$(((uptime_seconds % 86400) / 3600 ))
minutes=$(((uptime_seconds % 3600) / 60 ))
printf "%dd%dh%dm\n" $days $hours $minutes
