#!/bin/bash
uptime_seconds=$(awk '{print int($1)}' /proc/uptime)

days=$((uptime_seconds / 86400))
hours=$(((uptime_seconds % 86400) / 3600))
minutes=$(((uptime_seconds % 3600) / 60))

printf "%dd%dh%dm\n" "$days" "$hours" "$minutes"
